# Generated by Django 5.0.4 on 2024-04-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=100)),
                ('employeename', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('monthsalary', models.CharField(max_length=50)),
                ('workingdays', models.CharField(max_length=50)),
                ('salaryyear', models.CharField(max_length=50)),
                ('annualsalary', models.CharField(max_length=50)),
            ],
        ),
    ]
