# Generated by Django 5.0.4 on 2024-04-20 06:26

import emp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=emp.models.getFileName),
        ),
    ]
